/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
	"/api/auth/keys": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Api Keys */
		get: operations["list_api_keys_api_auth_keys_get"];
		put?: never;
		/** Create Api Key */
		post: operations["create_api_key_api_auth_keys_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/keys/{key_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Revoke Api Key */
		delete: operations["revoke_api_key_api_auth_keys__key_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/auth/me": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Me */
		get: operations["get_me_api_auth_me_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cli/auth/device": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Start Device Flow */
		post: operations["start_device_flow_api_cli_auth_device_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cli/auth/poll": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Poll Device Flow */
		post: operations["poll_device_flow_api_cli_auth_poll_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cli/auth/lookup": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Lookup Device Flow
		 * @description Web dashboard reads this to render the approve screen.
		 */
		get: operations["lookup_device_flow_api_cli_auth_lookup_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cli/auth/approve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Approve Device Flow */
		post: operations["approve_device_flow_api_cli_auth_approve_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/cli/auth/deny": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Deny Device Flow */
		post: operations["deny_device_flow_api_cli_auth_deny_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/environments": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Environments */
		get: operations["list_environments_api_environments_get"];
		put?: never;
		/** Register Environment */
		post: operations["register_environment_api_environments_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/environments/{environment_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Environment */
		get: operations["get_environment_api_environments__environment_id__get"];
		put?: never;
		post?: never;
		/**
		 * Delete Environment
		 * @description Delete an agent environment. Existing sessions remain (orphaned)
		 *     so users don't lose history when removing a machine. The session
		 *     list query uses an outer-join so orphaned rows still render.
		 */
		delete: operations["delete_environment_api_environments__environment_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sessions/batch": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Batch Create Sessions
		 * @description Ingest a batch of sessions from a CLI sync.
		 *
		 *     Upserts every row by `(user_id, local_session_id)`. The response tells
		 *     the client which sessions still need a content upload — either because
		 *     the stored hash differs from the one just sent, or because no content
		 *     has ever been uploaded for that row (`file_key IS NULL`).
		 */
		post: operations["batch_create_sessions_api_sessions_batch_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sessions": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Sessions */
		get: operations["list_sessions_api_sessions_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sessions/{session_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Session Detail */
		get: operations["get_session_detail_api_sessions__session_id__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sessions/{local_session_id}/upload": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Upload Session Content
		 * @description Upload session messages JSON to FileStore.
		 */
		post: operations["upload_session_content_api_sessions__local_session_id__upload_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sessions/{session_id}/content": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Session Content
		 * @description Read session messages from FileStore, typed as SessionMessageResponse[].
		 */
		get: operations["get_session_content_api_sessions__session_id__content_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/sessions/{local_session_id}/extract": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Extract Session Memories
		 * @description Extract memories from a session's content via the configured LLM.
		 *
		 *     Uses `local_session_id` for path lookup (mirrors the upload endpoint
		 *     pattern) — `uq_sessions_user_local` makes that a unique index.
		 *
		 *     Not idempotent — every call hits the LLM. Onboarding loops over
		 *     each session exactly once; the future dashboard button is a
		 *     user-initiated single click. Tracking "already extracted" state
		 *     on the server would force us to also reason about session updates
		 *     (re-pushed content with new turns), which is more complexity than
		 *     a one-shot $0.001 LLM call is worth.
		 */
		post: operations["extract_session_memories_api_sessions__local_session_id__extract_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/dashboard/stats": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Stats */
		get: operations["get_stats_api_dashboard_stats_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/dashboard/contribution": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Contribution Graph */
		get: operations["get_contribution_graph_api_dashboard_contribution_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/skills": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Skills */
		get: operations["list_skills_api_skills_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/skills/{skill_key}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Skill */
		get: operations["get_skill_api_skills__skill_key__get"];
		put?: never;
		post?: never;
		/** Delete Skill */
		delete: operations["delete_skill_api_skills__skill_key__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/skills/upload": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Upload Skill
		 * @description Upload a skill as a tar.gz archive.
		 */
		post: operations["upload_skill_api_skills_upload_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/skills/{skill_key}/download": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Download Skill
		 * @description Download skill as tar.gz archive.
		 */
		get: operations["download_skill_api_skills__skill_key__download_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/skills/install": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/** Install Skill */
		post: operations["install_skill_api_skills_install_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/memories": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Memories */
		get: operations["list_memories_api_memories_get"];
		put?: never;
		/** Create Memory */
		post: operations["create_memory_api_memories_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/memories/{memory_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Memory */
		get: operations["get_memory_api_memories__memory_id__get"];
		put?: never;
		post?: never;
		/** Delete Memory */
		delete: operations["delete_memory_api_memories__memory_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/memories/embed-backfill": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Embed Backfill
		 * @description Compute embeddings for the caller's memories that lack one.
		 *
		 *     Used after the deployment's embedder becomes available (first-time
		 *     install, or a model change). Uses the deployment-configured embedder
		 *     (env vars; see `app.core.config.Settings.memory_embedding_*`).
		 *
		 *     With `force=true`, re-embeds rows that already have embeddings too
		 *     (useful after changing the embedding model).
		 */
		post: operations["embed_backfill_api_memories_embed_backfill_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/settings": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** Get Settings */
		get: operations["get_settings_api_settings_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		/** Update Settings */
		patch: operations["update_settings_api_settings_patch"];
		trace?: never;
	};
	"/api/vault": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Vaults */
		get: operations["list_vaults_api_vault_get"];
		put?: never;
		/** Create Vault */
		post: operations["create_vault_api_vault_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/vault/{slug}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/** Delete Vault */
		delete: operations["delete_vault_api_vault__slug__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/vault/{slug}/items": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/** List Vault Sections */
		get: operations["list_vault_sections_api_vault__slug__items_get"];
		/** Upsert Vault Items */
		put: operations["upsert_vault_items_api_vault__slug__items_put"];
		post?: never;
		/** Delete Vault Items */
		delete: operations["delete_vault_items_api_vault__slug__items_delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/vault/resolve": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Resolve Vault
		 * @description Resolve all vault items to plaintext. CLI-only (requires ApiKey auth).
		 */
		post: operations["resolve_vault_api_vault_resolve_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Connections
		 * @description List user's connected services.
		 */
		get: operations["list_connections_api_connectors_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/available": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List Available Apps
		 * @description Paginated Composio app catalog. Server holds the full list in a
		 *     5-min in-process cache and slices per request, so paginating doesn't
		 *     cost a Composio roundtrip per page and the browser only ships one
		 *     page at a time. Search is substring across slug, display name, and
		 *     description (server-side, before pagination).
		 */
		get: operations["list_available_apps_api_connectors_available_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/available/{app_name}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Available App
		 * @description Single-app metadata lookup — used by the detail page so it doesn't
		 *     have to page through the whole catalog to find one app's display name.
		 *     Re-uses the cache that `/available` populates.
		 */
		get: operations["get_available_app_api_connectors_available__app_name__get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/{app_name}/connect": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Connect App
		 * @description Generate OAuth connect link for an app.
		 *
		 *     Forwards `body.redirect_url` to Composio so the OAuth provider
		 *     sends the user back to the caller's chosen landing page (e.g.
		 *     the connector detail page on the frontend). If omitted, Composio
		 *     falls back to its own managed callback.
		 */
		post: operations["connect_app_api_connectors__app_name__connect_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/{app_name}/auth-fields": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Auth Fields
		 * @description Return the auth scheme + credential fields for non-OAuth apps.
		 *
		 *     Used by the Connect dialog to render the right form (input names,
		 *     secret vs. plaintext, required markers). The frontend only opens
		 *     this dialog when the connector's `auth_type` is API-key style;
		 *     OAuth apps short-circuit to `window.open(connect_url)` instead.
		 */
		get: operations["auth_fields_api_connectors__app_name__auth_fields_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/{app_name}/connect-credentials": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Connect Credentials
		 * @description Create a connection from user-supplied API-key credentials.
		 *
		 *     The service polls Composio's `wait_until_active` (capped at 15s) so
		 *     a 200 here means the connection is ACTIVE — the frontend can render
		 *     it immediately without its own polling loop. Slow upstream auth
		 *     surfaces as 504.
		 */
		post: operations["connect_credentials_api_connectors__app_name__connect_credentials_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/{connection_id}": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		post?: never;
		/**
		 * Disconnect
		 * @description Disconnect a connected account.
		 *
		 *     Ownership guard: Composio identifies connections by id globally, so we
		 *     must confirm the connection belongs to this user before deleting it —
		 *     otherwise any authenticated user could delete anyone else's integration.
		 */
		delete: operations["disconnect_api_connectors__connection_id__delete"];
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/mcp-config": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Get Mcp Config
		 * @description Get MCP proxy config for the current user.
		 */
		get: operations["get_mcp_config_api_connectors_mcp_config_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/connectors/{app_name}/tools": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * List App Tools
		 * @description List available tools/actions for a specific app.
		 */
		get: operations["list_app_tools_api_connectors__app_name__tools_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/mcp/proxy": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		get?: never;
		put?: never;
		/**
		 * Mcp Proxy Post
		 * @description Handle MCP JSON-RPC requests using Composio SDK directly.
		 */
		post: operations["mcp_proxy_post_api_mcp_proxy_post"];
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/api/search": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Global Search
		 * @description Fan out to each entity searcher and concat results.
		 *
		 *     Each searcher returns at most `TYPE_LIMIT` rows; total is capped at
		 *     4*TYPE_LIMIT which keeps the palette responsive even with noisy queries.
		 *
		 *     Sessions/skills/vaults use `ILIKE` (small tables) — memories goes through
		 *     the hybrid provider (FTS + trgm + optional pgvector) for quality.
		 *
		 *     A single failing source (e.g. the memory provider briefly unavailable)
		 *     degrades to partial results rather than failing the whole request —
		 *     palette UX beats strict all-or-nothing consistency here.
		 */
		get: operations["global_search_api_search_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
	"/health": {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		/**
		 * Health
		 * @description Liveness + DB connectivity probe.
		 *
		 *     Returns 200 + ``{"status": "ok"}`` on success. If the DB is unreachable
		 *     the dependency raises and FastAPI returns 500 — the right signal for a
		 *     load balancer to yank this pod out of rotation.
		 */
		get: operations["health_health_get"];
		put?: never;
		post?: never;
		delete?: never;
		options?: never;
		head?: never;
		patch?: never;
		trace?: never;
	};
}
export type webhooks = Record<string, never>;
export interface components {
	schemas: {
		/** ApiKeyCreate */
		ApiKeyCreate: {
			/** Label */
			label: string;
		};
		/**
		 * ApiKeyCreated
		 * @description Returned only on creation — includes the raw key (shown once).
		 */
		ApiKeyCreated: {
			/** Id */
			id: string;
			/** Label */
			label: string;
			/** Key Prefix */
			key_prefix: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Last Used At */
			last_used_at: string | null;
			/** Expires At */
			expires_at: string | null;
			/** Revoked At */
			revoked_at: string | null;
			/** Raw Key */
			raw_key: string;
		};
		/** ApiKeyResponse */
		ApiKeyResponse: {
			/** Id */
			id: string;
			/** Label */
			label: string;
			/** Key Prefix */
			key_prefix: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/** Last Used At */
			last_used_at: string | null;
			/** Expires At */
			expires_at: string | null;
			/** Revoked At */
			revoked_at: string | null;
		};
		/** ApiKeyRevokeResponse */
		ApiKeyRevokeResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "revoked";
		};
		/** Body_upload_session_content_api_sessions__local_session_id__upload_post */
		Body_upload_session_content_api_sessions__local_session_id__upload_post: {
			/** File */
			file: string;
		};
		/** Body_upload_skill_api_skills_upload_post */
		Body_upload_skill_api_skills_upload_post: {
			/** Skill Key */
			skill_key: string;
			/** File */
			file: string;
			/** Content Hash */
			content_hash?: string | null;
		};
		/**
		 * ConnectRequest
		 * @description OAuth connect-link request body.
		 *
		 *     `redirect_url` is the absolute URL Composio redirects the user
		 *     back to after the OAuth flow completes. The frontend supplies
		 *     its own connector detail page (e.g.
		 *     `https://cloud.example.com/connectors/gmail`); when omitted,
		 *     Composio uses its own managed callback. Bound the URL length so
		 *     we can't be talked into routing OAuth through an attacker-
		 *     controlled multi-megabyte redirect.
		 */
		ConnectRequest: {
			/** Redirect Url */
			redirect_url?: string | null;
		};
		/**
		 * ConnectorAuthFieldResponse
		 * @description One input expected from the user when connecting via API key.
		 */
		ConnectorAuthFieldResponse: {
			/** Name */
			name: string;
			/** Display Name */
			display_name: string;
			/**
			 * Description
			 * @default
			 */
			description: string;
			/**
			 * Type
			 * @default string
			 */
			type: string;
			/**
			 * Required
			 * @default true
			 */
			required: boolean;
			/**
			 * Is Secret
			 * @default false
			 */
			is_secret: boolean;
			/**
			 * Expected From Customer
			 * @default true
			 */
			expected_from_customer: boolean;
			/** Default */
			default?: string | null;
		};
		/**
		 * ConnectorAuthFieldsResponse
		 * @description Schema describing how the user should authenticate this connector.
		 */
		ConnectorAuthFieldsResponse: {
			/** Auth Scheme */
			auth_scheme: string;
			/** Expected Input Fields */
			expected_input_fields: components["schemas"]["ConnectorAuthFieldResponse"][];
		};
		/** ConnectorAvailableAppResponse */
		ConnectorAvailableAppResponse: {
			/** Name */
			name: string;
			/** Display Name */
			display_name: string;
			/** Logo */
			logo: string;
			/** Description */
			description: string;
			/**
			 * Auth Type
			 * @default oauth2
			 */
			auth_type: string;
		};
		/** ConnectorConnectResponse */
		ConnectorConnectResponse: {
			/** Connect Url */
			connect_url: string;
			/** Id */
			id: string;
		};
		/** ConnectorConnectionResponse */
		ConnectorConnectionResponse: {
			/** Id */
			id: string;
			/** App Name */
			app_name: string;
			/** Status */
			status: string;
			/** Created At */
			created_at: string;
			/** Account Display */
			account_display?: string | null;
		};
		/**
		 * ConnectorCredentialsConnectRequest
		 * @description User-supplied credentials for an API-key style connector.
		 *
		 *     Bounds picked to fit any sane API-key form (Composio's largest
		 *     schema we've seen has ~6 fields; a single API key fits well under
		 *     8KB) while rejecting payloads that don't look like credentials at
		 *     all. Caps protect against accidental large-blob submissions and
		 *     keep error logs / Composio request bodies small.
		 */
		ConnectorCredentialsConnectRequest: {
			/** Credentials */
			credentials: {
				[key: string]: string;
			};
		};
		/** ConnectorCredentialsConnectResponse */
		ConnectorCredentialsConnectResponse: {
			/** Id */
			id: string;
			/** Status */
			status: string;
			/** Ok */
			ok: boolean;
		};
		/** ConnectorDisconnectResponse */
		ConnectorDisconnectResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "disconnected";
		};
		/** ConnectorMcpConfigResponse */
		ConnectorMcpConfigResponse: {
			/** Mcp Url */
			mcp_url: string;
			/** Mcp Token */
			mcp_token: string;
		};
		/** ConnectorToolParametersResponse */
		ConnectorToolParametersResponse: {
			/** Properties */
			properties: {
				[key: string]: unknown;
			};
			/** Required */
			required: string[];
		};
		/** ConnectorToolResponse */
		ConnectorToolResponse: {
			/** Name */
			name: string;
			/** Display Name */
			display_name: string;
			/** Description */
			description: string;
			/** Is Deprecated */
			is_deprecated: boolean;
			/** App */
			app?: string | null;
			parameters?: components["schemas"]["ConnectorToolParametersResponse"] | null;
		};
		/** ContributionDayResponse */
		ContributionDayResponse: {
			/**
			 * Date
			 * Format: date
			 */
			date: string;
			/** Count */
			count: number;
			/** Level */
			level: number;
		};
		/** CurrentUserResponse */
		CurrentUserResponse: {
			/** Id */
			id: string;
			/** Email */
			email: string | null;
			/** Name */
			name: string | null;
			/**
			 * Auth Type
			 * @enum {string}
			 */
			auth_type: "api_key" | "clerk";
		};
		/** DashboardStatsResponse */
		DashboardStatsResponse: {
			/** Total Sessions */
			total_sessions: number;
			/** Total Messages */
			total_messages: number;
			/** Total Tokens */
			total_tokens: number;
			/** Active Days */
			active_days: number;
			/** Current Streak */
			current_streak: number;
			/** Longest Streak */
			longest_streak: number;
			/** Peak Hour */
			peak_hour: number;
			/** Favorite Model */
			favorite_model: string | null;
			/** Skills Count */
			skills_count: number;
			/** Memories Count */
			memories_count: number;
			/** Vault Count */
			vault_count: number;
			/** Vault Keys Count */
			vault_keys_count: number;
			/** Connectors Count */
			connectors_count: number;
		};
		/** DeviceApproveRequest */
		DeviceApproveRequest: {
			/** User Code */
			user_code: string;
		};
		/** DeviceDenyRequest */
		DeviceDenyRequest: {
			/** User Code */
			user_code: string;
		};
		/** DeviceLookupResponse */
		DeviceLookupResponse: {
			/** User Code */
			user_code: string;
			/** Client Label */
			client_label: string | null;
			/** Status */
			status: string;
			/**
			 * Expires At
			 * Format: date-time
			 */
			expires_at: string;
		};
		/** DevicePollRequest */
		DevicePollRequest: {
			/** Device Code */
			device_code: string;
		};
		/** DevicePollResponse */
		DevicePollResponse: {
			/**
			 * Status
			 * @enum {string}
			 */
			status: "pending" | "approved" | "denied" | "expired";
			/** Api Key */
			api_key?: string | null;
		};
		/** DeviceStartRequest */
		DeviceStartRequest: {
			/** Client Label */
			client_label?: string | null;
		};
		/** DeviceStartResponse */
		DeviceStartResponse: {
			/** Device Code */
			device_code: string;
			/** User Code */
			user_code: string;
			/** Verification Uri */
			verification_uri: string;
			/** Expires In */
			expires_in: number;
			/** Interval */
			interval: number;
		};
		/** DeviceTerminalResponse */
		DeviceTerminalResponse: {
			/**
			 * Status
			 * @enum {string}
			 */
			status: "approved" | "denied";
		};
		/** EmbedBackfillResponse */
		EmbedBackfillResponse: {
			/** Processed */
			processed: number;
			/** Failed */
			failed: number;
		};
		/** EnvironmentCreate */
		EnvironmentCreate: {
			/** Machine Id */
			machine_id: string;
			/** Machine Name */
			machine_name: string;
			/** Agent Type */
			agent_type: string;
			/** Agent Version */
			agent_version?: string | null;
			/** Os */
			os: string;
		};
		/** EnvironmentCreatedResponse */
		EnvironmentCreatedResponse: {
			/** Id */
			id: string;
		};
		/** EnvironmentResponse */
		EnvironmentResponse: {
			/** Id */
			id: string;
			/** Machine Name */
			machine_name: string;
			/** Agent Type */
			agent_type: string;
			/** Agent Version */
			agent_version: string | null;
			/** Os */
			os: string;
			/** Last Seen At */
			last_seen_at: string | null;
		};
		/** HTTPValidationError */
		HTTPValidationError: {
			/** Detail */
			detail?: components["schemas"]["ValidationError"][];
		};
		/** MemoryCreate */
		MemoryCreate: {
			/** Content */
			content: string;
			/**
			 * Category
			 * @default fact
			 */
			category: string;
			/**
			 * Source
			 * @default manual
			 */
			source: string;
			/** Tags */
			tags?: string[] | null;
		};
		/** MemoryCreatedResponse */
		MemoryCreatedResponse: {
			/** Id */
			id: string;
		};
		/** MemoryDeleteResponse */
		MemoryDeleteResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "deleted";
		};
		/** MemoryResponse */
		MemoryResponse: {
			/** Id */
			id: string;
			/** Content */
			content: string;
			/** Category */
			category: string;
			/** Source */
			source: string;
			/** Tags */
			tags?: string[] | null;
			/** Access Count */
			access_count?: number | null;
			/** Created At */
			created_at?: string | null;
		};
		/** Paginated[ConnectorAvailableAppResponse] */
		Paginated_ConnectorAvailableAppResponse_: {
			/** Items */
			items: components["schemas"]["ConnectorAvailableAppResponse"][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Page Size */
			page_size: number;
		};
		/** Paginated[MemoryResponse] */
		Paginated_MemoryResponse_: {
			/** Items */
			items: components["schemas"]["MemoryResponse"][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Page Size */
			page_size: number;
		};
		/** Paginated[SessionListItemResponse] */
		Paginated_SessionListItemResponse_: {
			/** Items */
			items: components["schemas"]["SessionListItemResponse"][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Page Size */
			page_size: number;
		};
		/** Paginated[SkillSummaryResponse] */
		Paginated_SkillSummaryResponse_: {
			/** Items */
			items: components["schemas"]["SkillSummaryResponse"][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Page Size */
			page_size: number;
		};
		/** Paginated[VaultResponse] */
		Paginated_VaultResponse_: {
			/** Items */
			items: components["schemas"]["VaultResponse"][];
			/** Total */
			total: number;
			/** Page */
			page: number;
			/** Page Size */
			page_size: number;
		};
		/** SearchHit */
		SearchHit: {
			/**
			 * Type
			 * @enum {string}
			 */
			type: "session" | "memory" | "skill" | "vault";
			/** Id */
			id: string;
			/** Title */
			title: string;
			/** Subtitle */
			subtitle?: string | null;
			/** Href */
			href: string;
		};
		/** SearchResponse */
		SearchResponse: {
			/** Query */
			query: string;
			/** Results */
			results: components["schemas"]["SearchHit"][];
		};
		/** SessionBatchRequest */
		SessionBatchRequest: {
			/** Sessions */
			sessions: components["schemas"]["SessionCreate"][];
		};
		/** SessionBatchResponse */
		SessionBatchResponse: {
			/** Created */
			created: number;
			/** Updated */
			updated: number;
			/** Unchanged */
			unchanged: number;
			/** Needs Content */
			needs_content: string[];
		};
		/** SessionCreate */
		SessionCreate: {
			/**
			 * Environment Id
			 * Format: uuid
			 */
			environment_id: string;
			/** Local Session Id */
			local_session_id: string;
			/** Project Path */
			project_path?: string | null;
			/**
			 * Started At
			 * Format: date-time
			 */
			started_at: string;
			/** Ended At */
			ended_at?: string | null;
			/** Duration Seconds */
			duration_seconds?: number | null;
			/**
			 * Message Count
			 * @default 0
			 */
			message_count: number;
			/**
			 * Input Tokens
			 * @default 0
			 */
			input_tokens: number;
			/**
			 * Output Tokens
			 * @default 0
			 */
			output_tokens: number;
			/**
			 * Cache Read Tokens
			 * @default 0
			 */
			cache_read_tokens: number;
			/** Model */
			model?: string | null;
			/** Models Used */
			models_used?: string[] | null;
			/** Summary */
			summary?: string | null;
			/** Tags */
			tags?: string[] | null;
			/**
			 * Status
			 * @default completed
			 */
			status: string;
			/** Content Hash */
			content_hash?: string | null;
		};
		/** SessionDetailResponse */
		SessionDetailResponse: {
			/** Id */
			id: string;
			/** Local Session Id */
			local_session_id: string;
			/** Project Path */
			project_path: string | null;
			/** Agent Type */
			agent_type: string | null;
			/** Machine Name */
			machine_name?: string | null;
			/**
			 * Started At
			 * Format: date-time
			 */
			started_at: string;
			/** Ended At */
			ended_at: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Duration Seconds */
			duration_seconds: number | null;
			/** Message Count */
			message_count: number;
			/** Input Tokens */
			input_tokens: number;
			/** Output Tokens */
			output_tokens: number;
			/** Cache Read Tokens */
			cache_read_tokens: number;
			/** Model */
			model: string | null;
			/** Models Used */
			models_used: string[] | null;
			/** Summary */
			summary: string | null;
			/** Tags */
			tags: string[] | null;
			/** Status */
			status: string;
			/** Content Hash */
			content_hash?: string | null;
			/** Has Content */
			has_content: boolean;
		};
		/**
		 * SessionExtractResponse
		 * @description Result of `POST /api/sessions/{local_session_id}/extract`.
		 */
		SessionExtractResponse: {
			/** Memories Created */
			memories_created: number;
		};
		/** SessionListItemResponse */
		SessionListItemResponse: {
			/** Id */
			id: string;
			/** Local Session Id */
			local_session_id: string;
			/** Project Path */
			project_path: string | null;
			/** Agent Type */
			agent_type: string | null;
			/** Machine Name */
			machine_name?: string | null;
			/**
			 * Started At
			 * Format: date-time
			 */
			started_at: string;
			/** Ended At */
			ended_at: string | null;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Duration Seconds */
			duration_seconds: number | null;
			/** Message Count */
			message_count: number;
			/** Input Tokens */
			input_tokens: number;
			/** Output Tokens */
			output_tokens: number;
			/** Cache Read Tokens */
			cache_read_tokens: number;
			/** Model */
			model: string | null;
			/** Models Used */
			models_used: string[] | null;
			/** Summary */
			summary: string | null;
			/** Tags */
			tags: string[] | null;
			/** Status */
			status: string;
			/** Content Hash */
			content_hash?: string | null;
		};
		/**
		 * SessionMessageResponse
		 * @description One agent message inside a session content file.
		 *
		 *     Mirrors the shape the CLI writes via `clawdi push` — the JSON stored
		 *     in the file store is a list of these. Declared here so it lives in the
		 *     OpenAPI schema and flows through to generated TS types; keeps the frontend
		 *     from having to maintain a parallel interface.
		 */
		SessionMessageResponse: {
			/**
			 * Role
			 * @enum {string}
			 */
			role: "user" | "assistant";
			/** Content */
			content: string;
			/** Model */
			model?: string | null;
			/** Timestamp */
			timestamp?: string | null;
		};
		/** SessionUploadResponse */
		SessionUploadResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "uploaded";
			/** File Key */
			file_key: string;
			/** Content Hash */
			content_hash: string;
		};
		/** SettingsResponse */
		SettingsResponse: {
			[key: string]: unknown;
		};
		/** SettingsUpdate */
		SettingsUpdate: {
			/** Settings */
			settings: {
				[key: string]: unknown;
			};
		};
		/** SettingsUpdateResponse */
		SettingsUpdateResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "updated";
		};
		/** SkillDeleteResponse */
		SkillDeleteResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "deleted";
		};
		/** SkillDetailResponse */
		SkillDetailResponse: {
			/** Id */
			id: string;
			/** Skill Key */
			skill_key: string;
			/** Name */
			name: string;
			/** Description */
			description: string | null;
			/** Version */
			version: number;
			/** Source */
			source: string;
			/** Source Repo */
			source_repo: string | null;
			/** File Count */
			file_count: number | null;
			/** Content */
			content: string | null;
			/** Agent Types */
			agent_types: string[] | null;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
		};
		/** SkillInstallRequest */
		SkillInstallRequest: {
			/** Repo */
			repo: string;
			/** Path */
			path?: string | null;
		};
		/** SkillInstallResponse */
		SkillInstallResponse: {
			/** Skill Key */
			skill_key: string;
			/** Name */
			name: string;
			/** Description */
			description: string | null;
			/** Version */
			version: number;
			/** File Count */
			file_count: number;
			/** Repo */
			repo: string;
		};
		/** SkillSummaryResponse */
		SkillSummaryResponse: {
			/** Id */
			id: string;
			/** Skill Key */
			skill_key: string;
			/** Name */
			name: string;
			/** Description */
			description: string | null;
			/** Version */
			version: number;
			/** Source */
			source: string;
			/** Source Repo */
			source_repo: string | null;
			/** Agent Types */
			agent_types: string[] | null;
			/** File Count */
			file_count: number | null;
			/** Content Hash */
			content_hash: string;
			/** Is Active */
			is_active: boolean;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
			/**
			 * Updated At
			 * Format: date-time
			 */
			updated_at: string;
			/** Content */
			content?: string | null;
		};
		/** SkillUploadResponse */
		SkillUploadResponse: {
			/** Skill Key */
			skill_key: string;
			/** Name */
			name: string;
			/** Version */
			version: number;
			/** File Count */
			file_count: number;
		};
		/** ValidationError */
		ValidationError: {
			/** Location */
			loc: (string | number)[];
			/** Message */
			msg: string;
			/** Error Type */
			type: string;
			/** Input */
			input?: unknown;
			/** Context */
			ctx?: Record<string, never>;
		};
		/** VaultCreate */
		VaultCreate: {
			/** Slug */
			slug: string;
			/** Name */
			name: string;
		};
		/** VaultCreatedResponse */
		VaultCreatedResponse: {
			/** Id */
			id: string;
			/** Slug */
			slug: string;
		};
		/** VaultDeleteResponse */
		VaultDeleteResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "deleted";
		};
		/** VaultItemDelete */
		VaultItemDelete: {
			/**
			 * Section
			 * @default
			 */
			section: string;
			/** Fields */
			fields: string[];
		};
		/** VaultItemUpsert */
		VaultItemUpsert: {
			/**
			 * Section
			 * @default
			 */
			section: string;
			/** Fields */
			fields: {
				[key: string]: string;
			};
		};
		/** VaultItemsDeleteResponse */
		VaultItemsDeleteResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "deleted";
		};
		/** VaultItemsUpsertResponse */
		VaultItemsUpsertResponse: {
			/**
			 * Status
			 * @constant
			 */
			status: "ok";
			/** Fields */
			fields: number;
		};
		/** VaultResolveResponse */
		VaultResolveResponse: {
			[key: string]: string;
		};
		/** VaultResponse */
		VaultResponse: {
			/** Id */
			id: string;
			/** Slug */
			slug: string;
			/** Name */
			name: string;
			/**
			 * Created At
			 * Format: date-time
			 */
			created_at: string;
		};
		/** VaultSectionsResponse */
		VaultSectionsResponse: {
			[key: string]: string[];
		};
	};
	responses: never;
	parameters: never;
	requestBodies: never;
	headers: never;
	pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
	list_api_keys_api_auth_keys_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyResponse"][];
				};
			};
		};
	};
	create_api_key_api_auth_keys_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ApiKeyCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyCreated"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	revoke_api_key_api_auth_keys__key_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				key_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ApiKeyRevokeResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_me_api_auth_me_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["CurrentUserResponse"];
				};
			};
		};
	};
	start_device_flow_api_cli_auth_device_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DeviceStartRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeviceStartResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	poll_device_flow_api_cli_auth_poll_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DevicePollRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DevicePollResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	lookup_device_flow_api_cli_auth_lookup_get: {
		parameters: {
			query: {
				code: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeviceLookupResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	approve_device_flow_api_cli_auth_approve_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DeviceApproveRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeviceTerminalResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	deny_device_flow_api_cli_auth_deny_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["DeviceDenyRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DeviceTerminalResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	list_environments_api_environments_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EnvironmentResponse"][];
				};
			};
		};
	};
	register_environment_api_environments_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["EnvironmentCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EnvironmentCreatedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_environment_api_environments__environment_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				environment_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EnvironmentResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_environment_api_environments__environment_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				environment_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			204: {
				headers: {
					[name: string]: unknown;
				};
				content?: never;
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	batch_create_sessions_api_sessions_batch_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SessionBatchRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionBatchResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	list_sessions_api_sessions_get: {
		parameters: {
			query?: {
				/** @description Fuzzy search on summary/project/id */
				q?: string | null;
				/** @description Filter by agent_type */
				agent?: string | null;
				/** @description Filter by agent environment */
				environment_id?: string | null;
				sort?: string;
				order?: string;
				page?: number;
				page_size?: number;
				since?: string | null;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Paginated_SessionListItemResponse_"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_session_detail_api_sessions__session_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionDetailResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	upload_session_content_api_sessions__local_session_id__upload_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				local_session_id: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"multipart/form-data": components["schemas"]["Body_upload_session_content_api_sessions__local_session_id__upload_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionUploadResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_session_content_api_sessions__session_id__content_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionMessageResponse"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	extract_session_memories_api_sessions__local_session_id__extract_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				local_session_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SessionExtractResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_stats_api_dashboard_stats_get: {
		parameters: {
			query?: {
				days?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["DashboardStatsResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_contribution_graph_api_dashboard_contribution_get: {
		parameters: {
			query?: {
				days?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ContributionDayResponse"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	list_skills_api_skills_get: {
		parameters: {
			query?: {
				/** @description Search name / description / skill_key */
				q?: string | null;
				page?: number;
				page_size?: number;
				include_content?: boolean;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Paginated_SkillSummaryResponse_"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_skill_api_skills__skill_key__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillDetailResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_skill_api_skills__skill_key__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillDeleteResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	upload_skill_api_skills_upload_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"multipart/form-data": components["schemas"]["Body_upload_skill_api_skills_upload_post"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillUploadResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	download_skill_api_skills__skill_key__download_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				skill_key: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	install_skill_api_skills_install_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SkillInstallRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SkillInstallResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	list_memories_api_memories_get: {
		parameters: {
			query?: {
				page?: number;
				page_size?: number;
				category?: string | null;
				q?: string | null;
				order?: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Paginated_MemoryResponse_"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_memory_api_memories_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["MemoryCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemoryCreatedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_memory_api_memories__memory_id__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				memory_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemoryResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_memory_api_memories__memory_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				memory_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["MemoryDeleteResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	embed_backfill_api_memories_embed_backfill_post: {
		parameters: {
			query?: {
				/** @description Re-embed rows that already have an embedding. */
				force?: boolean;
				batch_size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["EmbedBackfillResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_settings_api_settings_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SettingsResponse"];
				};
			};
		};
	};
	update_settings_api_settings_patch: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["SettingsUpdate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SettingsUpdateResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	list_vaults_api_vault_get: {
		parameters: {
			query?: {
				/** @description Filter by slug / name */
				q?: string | null;
				page?: number;
				page_size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Paginated_VaultResponse_"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	create_vault_api_vault_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["VaultCreate"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VaultCreatedResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_vault_api_vault__slug__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VaultDeleteResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	list_vault_sections_api_vault__slug__items_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				slug: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VaultSectionsResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	upsert_vault_items_api_vault__slug__items_put: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["VaultItemUpsert"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VaultItemsUpsertResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	delete_vault_items_api_vault__slug__items_delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				slug: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["VaultItemDelete"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VaultItemsDeleteResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	resolve_vault_api_vault_resolve_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["VaultResolveResponse"];
				};
			};
		};
	};
	list_connections_api_connectors_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorConnectionResponse"][];
				};
			};
		};
	};
	list_available_apps_api_connectors_available_get: {
		parameters: {
			query?: {
				search?: string | null;
				page?: number;
				page_size?: number;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["Paginated_ConnectorAvailableAppResponse_"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_available_app_api_connectors_available__app_name__get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				app_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorAvailableAppResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	connect_app_api_connectors__app_name__connect_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				app_name: string;
			};
			cookie?: never;
		};
		requestBody?: {
			content: {
				"application/json": components["schemas"]["ConnectRequest"] | null;
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorConnectResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	auth_fields_api_connectors__app_name__auth_fields_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				app_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorAuthFieldsResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	connect_credentials_api_connectors__app_name__connect_credentials_post: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				app_name: string;
			};
			cookie?: never;
		};
		requestBody: {
			content: {
				"application/json": components["schemas"]["ConnectorCredentialsConnectRequest"];
			};
		};
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorCredentialsConnectResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	disconnect_api_connectors__connection_id__delete: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				connection_id: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorDisconnectResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	get_mcp_config_api_connectors_mcp_config_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorMcpConfigResponse"];
				};
			};
		};
	};
	list_app_tools_api_connectors__app_name__tools_get: {
		parameters: {
			query?: never;
			header?: never;
			path: {
				app_name: string;
			};
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["ConnectorToolResponse"][];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	mcp_proxy_post_api_mcp_proxy_post: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": unknown;
				};
			};
		};
	};
	global_search_api_search_get: {
		parameters: {
			query: {
				q: string;
			};
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["SearchResponse"];
				};
			};
			/** @description Validation Error */
			422: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": components["schemas"]["HTTPValidationError"];
				};
			};
		};
	};
	health_health_get: {
		parameters: {
			query?: never;
			header?: never;
			path?: never;
			cookie?: never;
		};
		requestBody?: never;
		responses: {
			/** @description Successful Response */
			200: {
				headers: {
					[name: string]: unknown;
				};
				content: {
					"application/json": {
						[key: string]: string;
					};
				};
			};
		};
	};
}
